export default [
  'Alcohol',
  'Amoeba',
  'Arsenic',
  'Arson',
  'Axe',
  'Bamboo Tip',
  'Baseball Bat',
  'Belt',
  'Bite And Tear',
  'Blender',
  'Blood Release',
  'Box Cutter',
  'Brick',
  'Bury',
  'Candlestick',
  'Chainsaw',
  'Chemicals',
  'Cleaver',
  'Crutch',
  'Dagger',
  'Dirty Water',
  'Dismember',
  'Drill',
  'Drown',
  'Dumbbell',
  'E-Bike',
  'Electric Baton',
  'Electric Current',
  'Explosives',
  'Folding Chair',
  'Gunpowder',
  'Hammer',
  'Hook',
  'Ice Skates',
  'Illegal Drug',
  'Injection',
  'Kerosene',
  'Kick',
  'Knife And Fork',
  'Lighter',
  'Liquid Drug',
  'Locked Room',
  'Machete',
  'Machine',
  'Mad Dog',
  'Match',
  'Mercury',
  'Metal Chain',
  'Metal Wire',
  'Overdose',
  'Packing Tape',
  'Pesticide',
  'Pill',
  'Pillow',
  'Pistol',
  'Plague',
  'Plastic Bag',
  'Poisonous Gas',
  'Poisonous Needle',
  'Potted Plant',
  'Powder Drug',
  'Punch',
  'Push',
  'Radiation',
  'Razor Blade',
  'Rope',
  'Scarf',
  'Scissors',
  'Sculpture',
  'Smoke',
  'Sniper',
  'Starvation',
  'Steel Tube',
  'Stone',
  'Sulfuric Acid',
  'Surgery',
  'Throat Slit',
  'Towel',
  'Trophy',
  'Trowel',
  'Unarmed',
  'Venomous Scorpion',
  'Venomous Snake',
  'Vampire Bat',
  'Video Game Console',
  'Virus',
  'Whip',
  'Wine',
  'Wire',
  'Work',
  'Wrench',

  // Undercover Allies Expansion
  'Arrow',
  'Assault Rifle',
  'Balloon',
  'Bank Vault',
  'Barbecue Fork',
  'Bear Trap',
  'Bees',
  'Black Widow',
  'Blood Sample',
  'Boiling Water',
  'Bus',
  'Car',
  'Chicken Bone',
  'Controlled Demolition',
  'Crowbar',
  'Dart Frog',
  'Dehydration',
  'Delivery Van',
  'Dirty Hands',
  'Dirty Needle',
  'Faulty Parachute',
  'Freezer',
  'Gas Leak',
  'Hot Tar',
  'Infection',
  'Killer Robot',
  'Leather Strap',
  'Medical Waste',
  'Microwave Oven',
  'Mold',
  'Mustard Gas',
  'Nanobots',
  'Net',
  'Oil Soaked Rags',
  'Old Blankets',
  'Peanut',
  'Plastic Wrap',
  'Poison Dart',
  'Rusty Nail',
  'Safe',
  'Sauna',
  'Saw',
  'Sewer Rat',
  'Sharpened Fan',
  'Shiv',
  'Soup Can',
  'Steamroller',
  'Sword',
  'Tear Gas',
  'Throwing Knives',
  'Throwing Stars',
  'Tick',
  'Tire Iron',
  'Undercooked Chicken',
];
