const Tile = require('./tile');

module.exports = [
  {
    label: 'Social Relationship',
    options: [
      'Relatives',
      'Friends',
      'Colleagues',
      'Employer/Employee',
      'Lovers',
      'Strangers',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Victim\'s Build',
    options: [
      'Large',
      'Thin',
      'Tall',
      'Short',
      'Disfigured',
      'Fit',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Sudden Incident',
    options: [
      'Power Failure',
      'Fire',
      'Conflict',
      'Loss of Valuables',
      'Scream',
      'Nothing',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Victim\'s Identity',
    options: [
      'Child',
      'Young Adult',
      'Middle-Aged',
      'Senior',
      'Male',
      'Female',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Personality',
    options: [
      'Arrogant',
      'Despicable',
      'Furious',
      'Greedy',
      'Forceful',
      'Perverted',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Trace at the Scene',
    options: [
      'Fingerprint',
      'Footprint',
      'Bruise',
      'Blood Stain',
      'Bodily Fluid',
      'Scar',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Hint on Corpse',
    options: [
      'Head',
      'Chest',
      'Hand',
      'Leg',
      'Partial',
      'All-over',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Victim\'s Expression',
    options: [
      'Peaceful',
      'Struggling',
      'Frightened',
      'In Pain',
      'Blank',
      'Angry',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Victim\'s Clothes',
    options: [
      'Neat',
      'Untidy',
      'Elegant',
      'Shabby',
      'Bizarre',
      'Naked',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'In Progress',
    options: [
      'Entertainment',
      'Relaxation',
      'Assembly',
      'Trading',
      'Visit',
      'Dining',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'State of the Scene',
    options: [
      'Bits and Pieces',
      'Ashes',
      'Water Stain',
      'Cracked',
      'Disorderly',
      'Tidy',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Duration of Crime',
    options: [
      'Instantaneous',
      'Brief',
      'Gradual',
      'Prolonged',
      'Few Days',
      'Unclear',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Evidence Left Behind',
    options: [
      'Natural',
      'Artistic',
      'Written',
      'Synthetic',
      'Personal',
      'Unrelated',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Weather',
    options: [
      'Sunny',
      'Stormy',
      'Dry',
      'Humid',
      'Cold',
      'Hot',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Time of Death',
    options: [
      'Dawn',
      'Morning',
      'Noon',
      'Afternoon',
      'Evening',
      'Night',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Corpse Condition',
    options: [
      'Still Warm',
      'Stiff',
      'Decayed',
      'Incomplete',
      'Intact',
      'Twisted',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'Noticed by Bystander',
    options: [
      'Sudden sound',
      'Prolonged sound',
      'Smell',
      'Visual',
      'Action',
      'Nothing',
    ],
    type: Tile.TYPE_SCENE,
  },
  {
    label: 'General Impression',
    options: [
      'Common',
      'Creative',
      'Fishy',
      'Cruel',
      'Horrible',
      'Suspenseful',
    ],
    type: Tile.TYPE_SCENE,
  },
];
